### ISSUE TITLE
I figured out why your paddles aren't showing up

### ISSUE THREAD

**Issue by miller-time** [atamis/pong-buffer-bug#1]
I found this repo via amethyst/amethyst#1217

I don't think the buffers mentioned in that issue are the reason your paddles aren't showing up. I see lots of buffers getting created in my console, but I was able to complete the entire tutorial.

I made the following change to your code and I'm seeing paddles when I run it:

```diff
     let pipe = Pipeline::build()
         .with_stage(
-            Stage::with_backbuffer().clear_target([0.0, 0.0, 0.0, 1.0], 0.0).with_pass(DrawFlat2D::new())
+            Stage::with_backbuffer().clear_target([0.0, 0.0, 0.0, 1.0], 1.0).with_pass(DrawFlat2D::new())
         );
```

As a side note, I spotted a different bug in your code:

```diff
     fn new(side: Side) -> Paddle {
         Paddle {
             side,
-            width: 1.0,
-            height: 1.0,
+            width: PADDLE_WIDTH,
+            height: PADDLE_HEIGHT,
         }
     }
 }
```

Cheers!

**Comment by atamis** [comment]
Hey, thanks so much for figuring this out, and sorry it was my own bug and not a real Amethyst bug. I think the buffers issue is a tad unnerving, but I'm glad to see it's not a blocker.
